.gitattributes: Add '* text=auto eol=lf'
By default, Git on Windows clones repositories with 'CRLF' line endings
instead of 'LF' line endings. This seemingly small detail can cause
people so much hell if they are running on Windows. I gladly have not
touched a Windows machine for a very long time. However, just for the
sake of history, here are some examples and the wonderful error
messages that accompany them:

Example 1:

   vscode ➜ /workspaces/vscode-remote-try-nix (main) $ ./.nix/ci/workflows/nix.sh
   /usr/bin/env: ‘nix\r’: No such file or directory

The culprit? 'CRLF' line endings in './.nix/ci/workflows/nix.sh'. After
converting it to 'LF', I really thought that now this goodam idiotic
truckload of shit should work. However, nope. Here we are again:

Example 2:

   vscode ➜ /workspaces/vscode-remote-try-nix (main) $ .nix/ci/workflows/nix.sh
   warning: Git tree '/workspaces/vscode-remote-try-nix' is dirty
   error: Cannot build '/nix/store/09icg6izpgm5546dbp4smnpwvvxnswsn-log.drv'.
          Reason: builder failed with exit code 2.
          Output paths:
            /nix/store/x12r8rksbx3h64sp63ngjwyfslsc88rd-log
          Last 1 log lines:
          > /nix/store/x12r8rksbx3h64sp63ngjwyfslsc88rd-log/bin/log: line 18: syntax error: unexpected end of file from `if' command on line 14
          For full logs, run:
            nix log /nix/store/09icg6izpgm5546dbp4smnpwvvxnswsn-log.drv
   error: Cannot build '/nix/store/pkwyismab8yg5p178a7nb75cm5h1q7d8-nix-shell-env.drv'.
          Reason: 1 dependency failed.
          Output paths:
            /nix/store/d44zh7yvfa9bwcinwajk3khqbdic8l64-nix-shell-env

I'm slowly starting to like Windows again. Because hey, why should it
work on Linux and Windows when it can only work on Linux?

However, it turned out 'flake.nix' also had 'CRLF' line endings. After
converting it to 'LF', everything finally worked as expected.

Example 3:

   vscode ➜ /workspaces/vscode-remote-try-nix (main) $ .nix/ci/workflows/nix.sh
   warning: Git tree '/workspaces/vscode-remote-try-nix' is dirty
    _________________
   < Nix is awesome! >
    -----------------
           \   ^__^
            \  (oo)\_______
               (__)\       )\/\
                   ||----w |
                   ||     ||

In order to prevent this nightmare from happening again and to keep
myself from growing that few extra gray hairs, create a '.gitattributes'
file and add the following configuration from StackOverflow [1]:

   * text=auto eol=lf

Link: https://stackoverflow.com/a/42136008 [1]
Signed-off-by: Stefan Kühnel <git@stefankuehnel.com>